// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANXsgQ_mZivy0Y0KC4lkEtyQG1CGklgrA',
    appId: '1:264700982137:web:8609f979d7743dc87775a8',
    messagingSenderId: '264700982137',
    projectId: 'rentapp-ca84f',
    authDomain: 'rentapp-ca84f.firebaseapp.com',
    storageBucket: 'rentapp-ca84f.firebasestorage.app',
    measurementId: 'G-9M6QSGPFGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTJox9jHNrMJxuUDuLmHlDbw0vRVePh-4',
    appId: '1:264700982137:android:4a80ddf107151e827775a8',
    messagingSenderId: '264700982137',
    projectId: 'rentapp-ca84f',
    storageBucket: 'rentapp-ca84f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAvOFKqSRG-5WtXTAax2AmZUIV_0ImLu8',
    appId: '1:264700982137:ios:71877898035fc54c7775a8',
    messagingSenderId: '264700982137',
    projectId: 'rentapp-ca84f',
    storageBucket: 'rentapp-ca84f.firebasestorage.app',
    iosBundleId: 'com.example.rentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAvOFKqSRG-5WtXTAax2AmZUIV_0ImLu8',
    appId: '1:264700982137:ios:71877898035fc54c7775a8',
    messagingSenderId: '264700982137',
    projectId: 'rentapp-ca84f',
    storageBucket: 'rentapp-ca84f.firebasestorage.app',
    iosBundleId: 'com.example.rentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANXsgQ_mZivy0Y0KC4lkEtyQG1CGklgrA',
    appId: '1:264700982137:web:dfbd04f051e627d17775a8',
    messagingSenderId: '264700982137',
    projectId: 'rentapp-ca84f',
    authDomain: 'rentapp-ca84f.firebaseapp.com',
    storageBucket: 'rentapp-ca84f.firebasestorage.app',
    measurementId: 'G-21MFJ1E3YS',
  );
}
